-- Futures Academy v1.1.2
-- Secure Owner Dashboard migration
-- Run this entire file once in Supabase SQL Editor.

begin;

-- Add persistent progression and moderation fields.
alter table public.profiles
  add column if not exists credits integer not null default 0,
  add column if not exists reputation integer not null default 0,
  add column if not exists banned boolean not null default false,
  add column if not exists suspended_until timestamptz,
  add column if not exists updated_at timestamptz not null default now();

-- Guard against negative grants.
alter table public.profiles
  drop constraint if exists profiles_xp_nonnegative,
  drop constraint if exists profiles_credits_nonnegative,
  drop constraint if exists profiles_reputation_nonnegative;

alter table public.profiles
  add constraint profiles_xp_nonnegative check (xp >= 0),
  add constraint profiles_credits_nonnegative check (credits >= 0),
  add constraint profiles_reputation_nonnegative check (reputation >= 0);

create index if not exists profiles_created_at_idx on public.profiles(created_at);
create index if not exists profiles_last_active_at_idx on public.profiles(last_active_at);
create index if not exists profiles_role_idx on public.profiles(role);

-- Record sensitive owner actions.
create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid not null references public.profiles(id) on delete restrict,
  target_user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_log enable row level security;

drop policy if exists "Owners view audit log" on public.admin_audit_log;
create policy "Owners view audit log"
on public.admin_audit_log
for select
to authenticated
using (public.is_owner());

-- Safe user activity heartbeat. A user can update only their own activity time.
create or replace function public.touch_last_active()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  update public.profiles
  set last_active_at = now(),
      updated_at = now()
  where id = auth.uid();
end;
$$;

revoke all on function public.touch_last_active() from public, anon;
grant execute on function public.touch_last_active() to authenticated;

-- Owner-only user list. Email is intentionally available only through this owner RPC.
create or replace function public.owner_list_users(
  search_text text default null,
  page_limit integer default 50,
  page_offset integer default 0
)
returns table (
  id uuid,
  email text,
  display_name text,
  role public.app_role,
  premium boolean,
  xp integer,
  credits integer,
  reputation integer,
  streak integer,
  banned boolean,
  suspended_until timestamptz,
  created_at timestamptz,
  last_active_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_owner() then
    raise exception 'Owner access required';
  end if;

  return query
  select
    p.id, p.email, p.display_name, p.role, p.premium,
    p.xp, p.credits, p.reputation, p.streak,
    p.banned, p.suspended_until, p.created_at, p.last_active_at
  from public.profiles p
  where
    search_text is null
    or btrim(search_text) = ''
    or p.email ilike '%' || btrim(search_text) || '%'
    or coalesce(p.display_name, '') ilike '%' || btrim(search_text) || '%'
  order by p.created_at desc
  limit greatest(1, least(page_limit, 100))
  offset greatest(0, page_offset);
end;
$$;

revoke all on function public.owner_list_users(text, integer, integer) from public, anon;
grant execute on function public.owner_list_users(text, integer, integer) to authenticated;

-- Owner-only platform totals.
create or replace function public.owner_platform_stats()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if not public.is_owner() then
    raise exception 'Owner access required';
  end if;

  select jsonb_build_object(
    'total_accounts', (select count(*) from public.profiles),
    'premium_users', (select count(*) from public.profiles where premium),
    'banned_users', (select count(*) from public.profiles where banned),
    'suspended_users', (
      select count(*) from public.profiles
      where suspended_until is not null and suspended_until > now()
    ),
    'active_24h', (
      select count(*) from public.profiles
      where last_active_at >= now() - interval '24 hours'
    ),
    'active_7d', (
      select count(*) from public.profiles
      where last_active_at >= now() - interval '7 days'
    ),
    'signups_today', (
      select count(*) from public.profiles
      where created_at >= date_trunc('day', now())
    ),
    'attempts_total', (select count(*) from public.attempts),
    'attempts_today', (
      select count(*) from public.attempts
      where created_at >= date_trunc('day', now())
    )
  ) into result;

  return result;
end;
$$;

revoke all on function public.owner_platform_stats() from public, anon;
grant execute on function public.owner_platform_stats() to authenticated;

-- Owner-only 14-day signup/activity chart.
create or replace function public.owner_daily_activity(days_back integer default 14)
returns table (
  activity_date date,
  signups bigint,
  active_users bigint,
  attempts bigint
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_owner() then
    raise exception 'Owner access required';
  end if;

  return query
  with dates as (
    select generate_series(
      current_date - (greatest(1, least(days_back, 90)) - 1),
      current_date,
      interval '1 day'
    )::date as day
  )
  select
    d.day,
    (select count(*) from public.profiles p where p.created_at::date = d.day),
    (select count(*) from public.profiles p where p.last_active_at::date = d.day),
    (select count(*) from public.attempts a where a.created_at::date = d.day)
  from dates d
  order by d.day;
end;
$$;

revoke all on function public.owner_daily_activity(integer) from public, anon;
grant execute on function public.owner_daily_activity(integer) to authenticated;

-- Centralized owner action function.
create or replace function public.owner_manage_user(
  target_user_id uuid,
  requested_action text,
  requested_value text default null,
  requested_amount integer default null
)
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  target public.profiles;
  normalized_action text := lower(btrim(requested_action));
  amount integer := coalesce(requested_amount, 0);
begin
  if not public.is_owner() then
    raise exception 'Owner access required';
  end if;

  if target_user_id = auth.uid()
     and normalized_action in ('ban', 'suspend', 'set_role') then
    if normalized_action <> 'set_role' or requested_value <> 'owner' then
      raise exception 'You cannot remove or restrict your own owner access';
    end if;
  end if;

  select * into target from public.profiles where id = target_user_id for update;
  if not found then
    raise exception 'User not found';
  end if;

  case normalized_action
    when 'set_role' then
      if requested_value not in ('user','moderator','admin','owner') then
        raise exception 'Invalid role';
      end if;
      update public.profiles
      set role = requested_value::public.app_role, updated_at = now()
      where id = target_user_id;

    when 'set_premium' then
      update public.profiles
      set premium = coalesce(requested_value::boolean, false), updated_at = now()
      where id = target_user_id;

    when 'ban' then
      update public.profiles
      set banned = true, suspended_until = null, updated_at = now()
      where id = target_user_id;

    when 'unban' then
      update public.profiles
      set banned = false, updated_at = now()
      where id = target_user_id;

    when 'suspend' then
      if amount < 1 or amount > 3650 then
        raise exception 'Suspension must be between 1 and 3650 days';
      end if;
      update public.profiles
      set suspended_until = now() + make_interval(days => amount),
          updated_at = now()
      where id = target_user_id;

    when 'unsuspend' then
      update public.profiles
      set suspended_until = null, updated_at = now()
      where id = target_user_id;

    when 'grant_xp' then
      if amount = 0 or abs(amount) > 1000000 then raise exception 'Invalid XP amount'; end if;
      update public.profiles
      set xp = greatest(0, xp + amount), updated_at = now()
      where id = target_user_id;

    when 'grant_credits' then
      if amount = 0 or abs(amount) > 1000000 then raise exception 'Invalid credits amount'; end if;
      update public.profiles
      set credits = greatest(0, credits + amount), updated_at = now()
      where id = target_user_id;

    when 'grant_reputation' then
      if amount = 0 or abs(amount) > 1000000 then raise exception 'Invalid reputation amount'; end if;
      update public.profiles
      set reputation = greatest(0, reputation + amount), updated_at = now()
      where id = target_user_id;

    else
      raise exception 'Unsupported owner action';
  end case;

  insert into public.admin_audit_log(actor_user_id, target_user_id, action, details)
  values (
    auth.uid(),
    target_user_id,
    normalized_action,
    jsonb_build_object(
      'value', requested_value,
      'amount', requested_amount
    )
  );

  select * into target from public.profiles where id = target_user_id;
  return target;
end;
$$;

revoke all on function public.owner_manage_user(uuid, text, text, integer) from public, anon;
grant execute on function public.owner_manage_user(uuid, text, text, integer) to authenticated;

-- Prevent normal browser clients from directly editing protected columns.
revoke update on public.profiles from authenticated;
grant update (display_name) on public.profiles to authenticated;

drop policy if exists "Users update own basic profile" on public.profiles;
drop policy if exists "Users update own safe profile fields" on public.profiles;

create policy "Users update own display profile"
on public.profiles
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

commit;
