-- Run this entire file in Supabase SQL Editor.

create type public.app_role as enum ('user', 'moderator', 'admin', 'owner');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text,
  role public.app_role not null default 'user',
  premium boolean not null default false,
  xp integer not null default 0,
  streak integer not null default 0,
  created_at timestamptz not null default now(),
  last_active_at timestamptz not null default now()
);

create table public.attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  scenario_type text not null,
  answer text not null,
  correct boolean not null,
  xp_awarded integer not null default 0,
  is_daily boolean not null default false,
  mistake_reason text,
  created_at timestamptz not null default now()
);

create table public.daily_completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  challenge_date date not null default current_date,
  correct boolean not null,
  xp_awarded integer not null default 0,
  created_at timestamptz not null default now(),
  unique(user_id, challenge_date)
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles(id, email, display_name)
  values(new.id, new.email, split_part(new.email, '@', 1));
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_staff()
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('moderator','admin','owner')
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('admin','owner')
  );
$$;

create or replace function public.is_owner()
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'owner'
  );
$$;

alter table public.profiles enable row level security;
alter table public.attempts enable row level security;
alter table public.daily_completions enable row level security;

create policy "Users view own profile"
on public.profiles for select
using (id = auth.uid() or public.is_admin());

create policy "Users update own basic profile"
on public.profiles for update
using (id = auth.uid() or public.is_admin())
with check (
  id = auth.uid()
  or public.is_admin()
);

create policy "Users insert own attempts"
on public.attempts for insert
with check (user_id = auth.uid());

create policy "Users read own attempts or admin reads all"
on public.attempts for select
using (user_id = auth.uid() or public.is_admin());

create policy "Users insert own daily completion"
on public.daily_completions for insert
with check (user_id = auth.uid());

create policy "Users read own daily completion or admin reads all"
on public.daily_completions for select
using (user_id = auth.uid() or public.is_admin());

-- Public leaderboard view omits email and private profile fields.
create or replace view public.leaderboard
with (security_invoker = true)
as
select
  id,
  coalesce(display_name, 'Trader') as display_name,
  xp,
  streak
from public.profiles
order by xp desc;

grant select on public.leaderboard to authenticated;

-- IMPORTANT:
-- After your first account is created, promote it once in SQL Editor:
-- update public.profiles set role='owner', premium=true where email='YOUR_EMAIL';


create table public.user_settings (
  user_id uuid primary key default auth.uid() references public.profiles(id) on delete cascade,
  sound_enabled boolean not null default true,
  reduced_motion boolean not null default false,
  updated_at timestamptz not null default now()
);

alter table public.user_settings enable row level security;

create policy "Users manage own settings"
on public.user_settings for all
using (user_id = auth.uid())
with check (user_id = auth.uid());
